name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: java1
      id: java1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: java1
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA1_RESULTS: "${{steps.java1.outputs.result}}"
      with:
        runners: java1
